### ISSUE TITLE
npm ERR! Failed at the ambi@2.2.0 preinstall script

### ISSUE THREAD

**Issue by brianzelip** [bevry/ambi#3]
Got the following error when installing [DocPad v6.69](https://docpad.org). Btw `sudo` was used for install.

node.js:815
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:815:23)
    at startup (node.js:58:13)
    at node.js:906:3
npm ERR! ambi@2.2.0 preinstall: `node ./cyclic.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the ambi@2.2.0 preinstall script.
npm ERR! This is most likely a problem with the ambi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ambi
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "docpad@6.69"
npm ERR! cwd /Users/brianzelip/Sites/sandbox/docpad
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by tomekwi** [comment]
Bump, I seem to have a very similar issue, but impossible to isolate and reproduce outside my project. It happens only on linux boxes, in a shrinkwrapped module, no matter what version of node. It might be an issue with npm.

Is it possible to get rid of the `npm install` hook? After all, https://docs.npmjs.com/misc/scripts#note-install-scripts-are-an-antipattern .

**Comment by balupton** [comment]
@tomekwi can you post the logs of what went wrong?

The script is necessary to fix cyclic dependencies in node.

**Comment by tomekwi** [comment]
@balupton, sure:

```sh
$ npm cache clean && rm -rf node_modules && npm install
 
> v8flags@1.0.8 install /home/tomekwi/the-project/node_modules/gulp/node_modules/v8flags
> node fetch.js

 
> typechecker@2.0.8 preinstall /home/tomekwi/the-project/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/typechecker
> node ./cyclic.js

 
> safefs@3.1.2 preinstall /home/tomekwi/the-project/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/safefs
> node ./cyclic.js

 
> taskgroup@4.0.5 preinstall /home/tomekwi/the-project/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/taskgroup
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /home/tomekwi/the-project/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js

npm ERR! cb() never called!
npm ERR! not ok code 0
```

This has been tested on three linux computers, always with the same result.

BTW, this works no problem:

```sh
$ npm cache clean && rm npm-shrinkwrap.json && rm -rf node_modules && npm install
```

I've finally managed to reproduce the problem – only by copying over the entire dependency tree! It's here in this repo: https://github.com/tomekwi/funny-npm-install-test

**Comment by balupton** [comment]
Hrmmm. What node and npm versions are you using?

```
node --version
npm --version
```

**Comment by tomekwi** [comment]
At the moment I'm running
```sh
$ node --version
v0.10.35
$ npm --version
1.4.28
```

But it's been tested with node v0.10.25, v0.10.30 and v0.10.33 – always the same result.

**Comment by tomekwi** [comment]
You can try it yourself:
```sh
$ git clone https://github.com/tomekwi/funny-npm-install-test && cd funny-npm-install-test && npm cache clean && npm install
```

Can you reproduce the problem this way?

**Comment by balupton** [comment]
Try with the latest npm, that npm is quite old. npm is on version 2 now

**Comment by balupton** [comment]
My logs:

```
01:01:21:balupton@balmac.local:/Users/balupton:master
$ nvm install v0.10.35
######################################################################## 100.0%
Now using node v0.10.35
01:01:59:balupton@balmac.local:/Users/balupton:master
$ nvm alias default 0.10
default -> 0.10 (-> v0.10.35)
01:02:05:balupton@balmac.local:/Users/balupton:master
$ npm i -g npm
/Users/balupton/.nvm/v0.10.35/bin/npm -> /Users/balupton/.nvm/v0.10.35/lib/node_modules/npm/bin/npm-cli.js
npm@2.2.0 /Users/balupton/.nvm/v0.10.35/lib/node_modules/npm
01:02:29:balupton@balmac.local:/Users/balupton:master
$ cd Projects 
01:02:33:balupton@balmac.local:/Users/balupton/Projects:master
$ git clone https://github.com/tomekwi/funny-npm-install-test && cd funny-npm-install-test && npm cache clean && npm install
Cloning into 'funny-npm-install-test'...
remote: Counting objects: 25, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 25 (delta 4), reused 10 (delta 1)
Unpacking objects: 100% (25/25), done.
Checking connectivity... done.
 
> v8flags@1.0.8 install /Users/balupton/Projects/funny-npm-install-test/node_modules/gulp/node_modules/v8flags
> node fetch.js

npm ERR! fetch failed https://registry.npmjs.org/clean-urls/-/clean-urls-1.1.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
npm ERR! fetch failed https://registry.npmjs.org/clean-urls/-/clean-urls-1.1.5.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 400
 
> typechecker@2.0.8 preinstall /Users/balupton/Projects/funny-npm-install-test/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/typechecker
> node ./cyclic.js

 
> safefs@3.1.2 preinstall /Users/balupton/Projects/funny-npm-install-test/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/safefs
> node ./cyclic.js

 
> taskgroup@4.0.5 preinstall /Users/balupton/Projects/funny-npm-install-test/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/taskgroup
> node ./cyclic.js

 
> ambi@2.2.0 preinstall /Users/balupton/Projects/funny-npm-install-test/node_modules/gulp-messageformat-bundle/node_modules/messageformat-bundle/node_modules/messageformat/node_modules/watchr/node_modules/taskgroup/node_modules/ambi
> node ./cyclic.js

format-json@1.0.3 node_modules/format-json

gulp-json-transform@0.2.0 node_modules/gulp-json-transform

mithril@0.1.28 node_modules/mithril

gulp-rename@1.2.0 node_modules/gulp-rename

as@0.2.0-alpha.2 node_modules/as

async@0.9.0 node_modules/async

gulp-es6-module@0.0.1 node_modules/gulp-es6-module
└── through@2.3.6

lazypipe@0.2.2 node_modules/lazypipe
└── stream-combiner@0.2.1 (duplexer@0.1.1, through@2.3.6)

gulp-sourcemaps@1.2.2 node_modules/gulp-sourcemaps
├── convert-source-map@0.4.1
└── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)

through2@0.6.3 node_modules/through2
├── xtend@4.0.0
└── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

gulp-plumber@0.6.4 node_modules/gulp-plumber
└── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)

minimatch@2.0.1 node_modules/minimatch
└── brace-expansion@1.1.0 (concat-map@0.0.1, balanced-match@0.2.0)

101@0.8.0 node_modules/101
├── extend@1.3.0
├── clone@0.1.19
├── keypather@1.8.1
└── deep-eql@0.1.3 (type-detect@0.1.1)

101-es6@0.8.0 node_modules/101-es6
├── extend@1.3.0
├── clone@0.1.19
├── keypather@1.8.1
└── deep-eql@0.1.3 (type-detect@0.1.1)

gulp-minify-css@0.3.10 node_modules/gulp-minify-css
├── memory-cache@0.0.5
├── clean-css@2.2.23 (commander@2.2.0)
└── bufferstreams@0.0.2 (readable-stream@1.0.33)

gulp-shell@0.2.10 node_modules/gulp-shell
├── lodash@2.4.1
└── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)

gulp-yaml@0.2.3 node_modules/gulp-yaml
├── extend@2.0.0
├── bufferstreams@0.0.2 (readable-stream@1.0.33)
└── js-yaml@3.2.5 (esprima@1.0.4, argparse@0.1.16)

gulp-mustache@1.0.0 node_modules/gulp-mustache
├── mustache@0.8.2
└── through2@1.1.1 (xtend@4.0.0, readable-stream@1.1.13)

del@1.0.0 node_modules/del
├── is-path-cwd@1.0.0
├── rimraf@2.2.8
├── each-async@1.1.1 (onetime@1.0.0, set-immediate-shim@1.0.0)
├── is-path-in-cwd@1.0.0 (is-path-inside@1.0.0)
└── globby@1.1.0 (array-union@1.0.1, glob@4.3.5)

gulp-uglify@1.0.1 node_modules/gulp-uglify
├── deepmerge@0.2.7
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── uglify-js@2.4.15 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.34, optimist@0.3.7)

traceur@0.0.72 node_modules/traceur
├── commander@2.6.0
├── semver@2.3.2
├── rsvp@3.0.16
├── glob@4.3.5 (inherits@2.0.1, once@1.3.1, inflight@1.0.4)
└── regexpu@0.3.0 (regjsgen@0.2.0, regenerate@1.0.1, regjsparser@0.1.3, recast@0.8.8)

gulp-util@3.0.1 node_modules/gulp-util
├── lodash._reinterpolate@2.4.1
├── minimist@1.1.0
├── lodash@2.4.1
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── multipipe@0.1.2 (duplexer2@0.0.2)
├── lodash.template@2.4.1 (lodash._escapestringchar@2.4.1, lodash.values@2.4.1, lodash.templatesettings@2.4.1, lodash.defaults@2.4.1, lodash.keys@2.4.1, lodash.escape@2.4.1)
└── dateformat@1.0.11 (get-stdin@3.0.2, meow@2.1.0)

gulp-beautify@1.1.1 node_modules/gulp-beautify
├── node-beautify@0.0.2
├── rcloader@0.1.2 (rcfinder@0.1.8, lodash@2.4.1)
├── event-stream@3.2.1 (duplexer@0.1.1, stream-combiner@0.0.4, from@0.1.3, pause-stream@0.0.11, map-stream@0.1.0, split@0.2.10, through@2.3.6)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, multipipe@0.1.2, through2@0.5.1, lodash.template@2.4.1, dateformat@1.0.11)

gulp-minify-html@0.1.7 node_modules/gulp-minify-html
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
├── minimize@0.10.1 (utile@0.2.1, htmlparser2@3.8.2)
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, multipipe@0.1.2, lodash.template@2.4.1, dateformat@1.0.11)

gulp-data-module@0.0.4 node_modules/gulp-data-module
└── data-module@0.0.4 (trimmer@1.0.0, extend@2.0.0, indent-string@1.2.0)

gulp-messageformat-bundle@0.0.4 node_modules/gulp-messageformat-bundle
├── basename@0.1.2
└── messageformat-bundle@0.0.3 (eval-expression@0.1.1, tosource@0.1.3, map-object-recursive@0.0.1, messageformat@0.2.1)

gulp-less@1.3.6 node_modules/gulp-less
├── convert-source-map@0.4.1
├── lodash.defaults@2.4.1 (lodash._objecttypes@2.4.1, lodash.keys@2.4.1)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
└── less@1.7.5 (graceful-fs@3.0.5, mime@1.2.11, mkdirp@0.5.0, source-map@0.1.43, clean-css@2.2.23, request@2.40.0)

gulp@3.8.10 node_modules/gulp
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.0
├── semver@4.2.0
├── v8flags@1.0.8
├── tildify@1.0.0 (user-home@1.1.1)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@0.13.6 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.1.3)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.5, strip-bom@1.0.0, defaults@1.0.0, vinyl@0.4.6, mkdirp@0.5.0, glob-stream@3.1.18, glob-watcher@0.0.6)

gulp-livereload@2.1.0 node_modules/gulp-livereload
├── tiny-lr@0.0.7 (debug@0.8.1, faye-websocket@0.4.4, qs@0.5.6, noptify@0.0.3)
├── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3, chalk@0.5.1, multipipe@0.1.2, through2@0.5.1, lodash.template@2.4.1, dateformat@1.0.11)
└── lodash.merge@2.4.1 (lodash._slice@2.4.1, lodash.isobject@2.4.1, lodash._getarray@2.4.1, lodash._releasearray@2.4.1, lodash._basemerge@2.4.1, lodash._basecreatecallback@2.4.1)

superstatic@1.1.6 node_modules/superstatic
├── caseless@0.7.0
├── file-exists@0.1.1
├── slashify@0.1.0
├── stacked@1.1.0
├── slasher@1.0.0
├── minimist@1.1.0
├── qs@2.3.3
├── lodash@2.4.1
├── connect-query@0.2.0 (qs@1.1.0)
├── mix-into@0.4.0 (deap@0.2.2)
├── mime-types@2.0.3 (mime-db@1.2.0)
├── fast-url-parser@1.1.1 (punycode@1.3.2)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── feedback@0.3.2 (chalk@0.3.0)
├── pretty-print@1.0.0 (lodash@2.2.1, chalk@0.3.0)
├── serve-favicon@2.1.6 (ms@0.6.2, fresh@0.2.4, etag@1.5.1)
├── compression@1.2.0 (on-headers@1.0.0, vary@1.0.0, bytes@1.0.0, compressible@2.0.1, accepts@1.1.4, debug@2.1.1)
├── cache-control@1.0.2 (lodash.isnumber@2.4.1, globject@1.0.1, regular@0.1.6, on-headers@1.0.0, glob-slasher@1.0.1)
├── morgan@1.5.0 (basic-auth@1.0.0, depd@1.0.0, debug@2.1.1, on-finished@2.1.1)
├── van@0.0.4 (chalk@0.4.0)
├── redirects@1.0.0 (globject@1.0.1, toxic@1.0.0, glob-slasher@1.0.1, lodash.isobject@2.4.1, pathematics@0.1.1)
├── connect@3.3.3 (utils-merge@1.0.0, parseurl@1.3.0, debug@2.1.1, finalhandler@0.3.2)
├── nash@0.5.2 (sorted-object@1.0.0, args-list@0.3.3, minimist@0.1.0, qmap@0.2.3, chalk@0.4.0, flat-arguments@0.3.0, drainer@0.2.1, pretty-print@0.4.1)
├── broker@1.0.1 (mime-types@1.0.2, deliver@1.1.10)
├── not-found@1.0.1 (is-url@1.2.0, deliver@1.1.10)
├── static-router@1.0.4 (directory-index@0.1.0, minimatch@1.0.0, glob-slasher@1.0.1, deliver@1.1.10, globject@1.0.1)
```

**Comment by balupton** [comment]
npm v2 and higher I suspect no longer need cyclic.js, as such in the next week or so it should be removed from all our projects

**Comment by tomekwi** [comment]
:+1: sorry, I must have missed your comments back then. I’ve now checked the thing with *npm v2.11.2* and it works like a charm. But it’s good news that *npm* handles circular deps out of the box!
